### ISSUE TITLE
Feature: Custom data in memo

### ISSUE THREAD

**Issue by showered** [kin-labs/kinetic#215]
In agora, developers can attach "invoices" to payments with the some extra information about the payment.

Title, description, sku.

I'm not sure we need to necessarily replicate this functionality exactly, but it would be great to be able to pass some extra data in the memo.

For example, something along the lines of:

```
type: "avatar_purchase"
identifier: "abc123"
```

Which would enable Web servers to easily look up the corresponding payment in their own database.

**Comment by beeman** [comment]
> In agora, developers can attach "invoices" to payments with the some extra information about the payment.
> 
> Title, description, sku.
> 
> I'm not sure we need to necessarily replicate this functionality exactly, but it would be great to be able to pass some extra data in the memo.
> 
> For example, something along the lines of:
> 
> ```
> type: "avatar_purchase"
> identifier: "abc123"
> ```
> 
> Which would enable Web servers to easily look up the corresponding payment in their own database.

Thanks for the suggestion - for our v1 release we don't change the memo field, so we'll keep this in the backlog.

**Comment by showered** [comment]
We now have this with `referenceType` and `referenceId`
