### ISSUE TITLE
Change MakeTransferRequest.tx to type Buffer

### ISSUE THREAD

**Issue by samdowd** [kin-labs/kinetic#231]
MakeTransferRequest.tx generates in iOS as an `Any` which because of a quirk in the iOS generation breaks the implementation. It seems it could instead be strongly typed as a Buffer to avoid that quirk and be more accurate in general.

**Comment by beeman** [comment]
@samdowd I pushed a branch #247 that might fix this. Could you test this locally and see what your iOS code generation gets you with this?

If you need a hand getting it running locally let me know. Probably quite some things changed since the last time you ran it.
