### ISSUE TITLE
AllExceptionsFilter hides GraphQL errors

### ISSUE THREAD

**Issue by beeman** [kin-labs/kinetic#255]
This is the GraphQL error

![image](https://user-images.githubusercontent.com/36491/173155973-25c01799-40ea-4dbb-887a-36d8aff58ccc.png)

But this is what ends up for the client.

![image](https://user-images.githubusercontent.com/36491/173155926-54c4f615-ef15-4806-af66-6e38393ed38c.png)

Things to consider:
- see if we can make the filter work with GraphQL
- disable the filter for any GraphQL requests

Tasks:
- [x] Figure out what `AllExceptionsFilter` did in the first place
- [x] Make sure we have tests that prove it working
- [x] Remove `AllExceptionsFilter` and replace with more specific filters
- [ ] Add tests to GraphQL that make sure we get the correct, unfiltered, output.

**Comment by RamirezAlex** [comment]
Closed by #268
