### ISSUE TITLE
Most AppTransaction fields should be optional

### ISSUE THREAD

**Issue by samdowd** [kin-labs/kinetic#265]
All AppTransaction fields are marked as required in the schema, causing iOS (at least) to panic when a transaction does not follow the happy path and is missing any one of them

**Comment by beeman** [comment]
@samdowd can you see if this fixes the panic in iOS? Feel free to open issues if you need this on any other fields. It makes our schema more specific which is good!

**Comment by samdowd** [comment]
@beeman confirmed fixed!
