### ISSUE TITLE
Add option to define different RPC providers for API and SDKs

### ISSUE THREAD

**Issue by beeman** [kin-labs/kinetic#291]
We need to be able to configure the Solana RPC endpoint URL in the Solana client in the Kinetic SDKs. 

We'll also add a way to separate the RPC provider that's used in the Kinetic API (private) from the Kinetic SDKs (public).

That way, we can add a cluster with a private endpoint to a paid RPC provider, while the local SDKs connect to the public, Solana-hosted RPCs. 

- [x] Add `endpointPrivate` property to the `Cluster` model
- [x] Ensure it is used instead of the current `endpoint` property
- [x] Add options in Admin to manage both properties
- [x] Expose the public endpoint property in the SDKs
- [x] Ensure the SDK is using the public endpoint

**Comment by RamirezAlex** [comment]
Closed by: #294
