### ISSUE TITLE
How do i use Kinetic in any react typescript project?

### ISSUE THREAD

**Issue by Griphcode** [kin-labs/kinetic#295]
I have a problem finding out how i can use Kinetic inside any of my React typescript projects. 
if you have an answer please be sure to let me know. It would really help!

**Comment by beeman** [comment]
Hi @Griphcode, thanks for your message! We're excited to see you are interested in Kinetic!

I just updated our demo app that you can find here: https://github.com/kin-starters/kinetic-react-starter

You can also reference the docs here https://kinetic.kin.org/docs/sdk/typescript

Please let us know if you have any questions or are stuck here or on the [Kin Developer Discord](https://discord.gg/kdRyUNmHDn).
