### ISSUE TITLE
Implement SDK filter for User Agents

### ISSUE THREAD

**Issue by beeman** [kin-labs/kinetic#356]
We need to be able to block and allow specific user agents (UA) per environment.

The initial iteration will only block making transactions. Later we will add this to more operations.

## Blocked UA management

- [x] add the `uasBlocked String[]` property to the [`AppEnv` model](https://github.com/kin-labs/kinetic/blob/dev/libs/api/core/data-access/src/prisma/schema.prisma#L42)
- [x] add the `ua String` property to the [`AppTransaction` model](https://github.com/kin-labs/kinetic/blob/dev/libs/api/core/data-access/src/prisma/schema.prisma#L83)
- [x] add the `uasBlocked` property to the [`AppEnv` entity](https://github.com/kin-labs/kinetic/blob/dev/libs/api/app/data-access/src/lib/entity/app-env.entity.ts)
- [x] make sure the property gets shown in the Admin by adding it to the [`AppEnvDetails` fragment](https://github.com/kin-labs/kinetic/blob/dev/libs/shared/util/admin-sdk/src/graphql/feature-app-fragments.graphql#L11)
- [x] add [GraphQL mutations](https://github.com/kin-labs/kinetic/blob/dev/libs/api/app/feature/src/lib/api-app-env-feature.resolver.ts) to add and remove blocked UAs
  - [x] `userAppEnvAddBlockedUa` - takes `appEnvId: string` and `ip: string` as an argument
  - [x] `userAppEnvRemoveBlockedUa` - takes `appEnvId: string` and `ip: string` as an argument
  - [x] add `api-e2e` tests to make sure the above works
- [x] add a simple UI below the `Webhook Settings` that shows
  - [x] any blocked UAs or a message if none is blocked
  - [x] a text input `ua` with a button `Block UA` that invokes `userAppEnvAddBlockedUa`
  - [x] a `Delete` button next to each blocked UA that invokes `userAppEnvRemoveBlockedUa`

## Blocking UAs

- [x] add the request to the [`makeTransfer` request operation](https://github.com/kin-labs/kinetic/blob/dev/libs/api/transaction/feature/src/lib/api-transaction-feature.controller.ts#L41) and pass it as the first argument in the [`makeTransfer` method](https://github.com/kin-labs/kinetic/blob/dev/libs/api/transaction/data-access/src/lib/api-transaction-data-access.service.ts#L151) in the service. (should be done in #357)
- [x] validate if the requesting UA does not exist in the `appEnv.uasBlocked` property and throw an `UnauthorizedException` if the UA is blocked.
- [x] persist the `ua` on the `AppTransaction` method if it's not blocked.

 ## Follow-up

- [x] create a follow-up story based on this one for the `uasAllowed` property, that works the opposite way.

**Comment by RamirezAlex** [comment]
At SDK level, provide the SDK name and version for any `makeTransfer` request.

Something like:
```js
sdk.makeTransfer({
  ...,
  sdkAgent: `node-1.0.0-rc.0`
})
```

Even better explore the idea of included in the generated code by default.

**Comment by beeman** [comment]
> At SDK level, provide the SDK name and version for any `makeTransfer` request.
> 
> Something like:
> 
> ```js
> sdk.makeTransfer({
>   ...,
>   sdkAgent: `node-1.0.0-rc.0`
> })
> ```
> 
> Even better explore the idea of include it in the generated code by default.

Doing this at the sdk level is outside of the scope.

The sdk will send along a user agent which we can block, we can later check how we set our own custom user agent in a follow-up story.
