### ISSUE TITLE
Change Kinetic API endpoints to only accept `environment` and `index` per header

### ISSUE THREAD

**Issue by beeman** [kin-labs/kinetic#419]
Currently, the environment is passed in in the PATH of the URL for most of the requests, but it's a bit weird and inconsistent. 

A cleaner solution would be to use the `kinetic-environment` and `kinetic-index` properties from the header that we already send with any request coming from the SDKs.

<img width="797" alt="image" src="https://user-images.githubusercontent.com/36491/190856657-da189592-49d8-4830-a9cb-179af4198d87.png">

The only downside I can think of is that you can't load up an endpoint in your browser, but considering this is not a _feature_ and is easy to replace with a `curl` request I think it's not a big deal.

**Comment by RamirezAlex** [comment]
@beeman this is interesting. We might want to revisit our current SDK generators and make sure they take in account the headers to generate the code without any issues. I believe all the ones that we are using so far are already stable versions, so it should be there. Perhaps the current ones that we are using support it, but also need to think about some future ones.
