### ISSUE TITLE
BUG (Admin): Unable to update RPC endpoint per cluster

### ISSUE THREAD

**Issue by showered** [kin-labs/kinetic#467]
The option to update the RPC endpoint does exist in the Admin UI, but it doesn't actually work. After updating the endpoint, transactions still use the previous RPC. The only way to update it is to change environment variable and restart the server.

**Comment by beeman** [comment]
I have looked at this and identified there are 2 main issues that we need a fix for, I listed them below.

I'm going to figure out a way to make sure it works as expected using the Admin, and we will find a way for local development. 

## Endpoint in DB is not used

The endpoint settings in the ENV Vars override settings from the database. In [this section](https://github.com/kin-labs/kinetic/blob/db9397d505ff68a3b96b3e444a15d2673a27aaf6/libs/api/core/data-access/src/lib/api-core-data-access.service.ts#L298-L303) we update all the values, except the `status` property. This works great in development as we can quickly switch endpoints. We need to improve this for production use cases though

## The new Endpoint is not used

The Kinetic API uses [this method](https://github.com/kin-labs/kinetic/blob/db9397d505ff68a3b96b3e444a15d2673a27aaf6/libs/api/core/data-access/src/lib/api-core-data-access.service.ts#L210-L222) to get the Solana connection for a certain app environment and caches it. After we update a cluster using the admin, we will need to find out to which App Environments it's connected, and remove those environments from the connection cache.

**Comment by beeman** [comment]
The second issue I listed above is pretty easy to fix, the second will need a bit more thinking as it will break/change the local workflow.

Sadly, fixing the second issue is not really helpful if the first one is not fixed, as a server restart will override the settings.

For now, the recommended way to define your cluster endpoints is using ENV VARS. 

We aim to have this fixed for v1.0.0.
